fixtures:
  forge_modules:
    firewall: "puppetlabs/firewall"
    stdlib: "puppetlabs/stdlib"
    concat:
        repo: "puppetlabs/concat"
        ref: 2.2.1
  symlinks:
    antelope: "#{source_dir}"
