fixtures:
  repositories:
    stdlib:
        repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
        ref: '4.11.0'
    concat: git://github.com/puppetlabs/puppet-concat.git
  symlinks:
    antelope: "#{source_dir}"
