spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
spec/default_facts.yml:
  extra_facts:
    antelope_contrib_basedir:
      '5.9': '/contrib'
      '5.10': '/contrib'
      '5.11': '/contrib'
      '5.12': '/contrib'
      '5.13': '/contrib'
      '5.14': '/contrib'
      '5.15': '/contrib'
    antelope_latest_perl: 'perl5.38.2'
    antelope_latest_python: 'python3.12.3'
    antelope_latest_version: '5.15'
    antelope_services: 'antelope'
    antelope_versions: '5.9,5.10,5.11,5.12,5.13,5.14,5.15'
    antelope_versions_array: ['5.9', '5.10', '5.11', '5.12', '5.13', '5.14', '5.15']
    antelope_versions_supports_aldproxy: '5.9,5.10,5.11,5.12,5.13,5.14,5.15'
    antelope_versions_supports_aldproxy_array: ['5.9', '5.10', '5.11', '5.12', '5.13', '5.14', '5.15']
Gemfile:
  optional:
    ':development':
      - gem: 'byebug'
        version: '~> 11.1'
      - gem: 'pry'
        version: '~> 0.14'
      - gem: 'pry-byebug'
        version: '~> 3.10'