name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run syntax validation
        run: bundle exec rake syntax

      - name: Run lint validation
        run: bundle exec rake lint

      - name: Run metadata validation
        run: bundle exec rake metadata_lint

  unit-tests:
    name: Unit Tests
    needs: validate
    strategy:
      fail-fast: false
      matrix:
        puppet_version:
          - '7'
          - '8'
        ruby_version:
          - '2.7.8'
          - '3.1.4'
        exclude:
          # Puppet 7 doesn't support Ruby 3.1
          - puppet_version: '7'
            ruby_version: '3.1.4'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Configure Puppet version
        run: bundle config set PUPPET_GEM_VERSION '~> ${{ matrix.puppet_version }}.0'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run unit tests
        run: bundle exec rake parallel_spec

  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      - name: Configure Puppet version
        run: bundle config set PUPPET_GEM_VERSION '~> 8.0'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run static analysis checks
        run: |
          bundle exec rake check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint

  comprehensive-tests:
    name: Comprehensive Test Suite
    needs: [validate, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'
          bundler-cache: true

      - name: Configure Puppet version
        run: bundle config set PUPPET_GEM_VERSION '~> 7.0'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run full Rake test suite
        run: bundle exec rake

      - name: Test shared utility module loading
        run: |
          bundle exec ruby -I lib -e "
            require 'antelope/version_utils'
            extend Antelope::VersionUtils
            puts 'Shared utility module loads correctly'
            result = compare_antelope_versions('5.4-64', '5.5')
            puts \"Version comparison test: #{result}\"
          "

      - name: Verify GitHub release automation
        run: |
          bundle exec rake ghrelease:validate || echo "GitHub CLI not available in CI - this is expected"

  cross-platform:
    name: Cross-platform Tests
    needs: validate
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        puppet_version: ['7', '8']
        include:
          - os: ubuntu-latest
            puppet_version: '7'
            ruby_version: '2.7.8'
          - os: ubuntu-latest
            puppet_version: '8'
            ruby_version: '3.1.4'
          - os: macos-latest
            puppet_version: '7'
            ruby_version: '2.7.8'
          - os: macos-latest
            puppet_version: '8'
            ruby_version: '3.1.4'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Configure Puppet version
        run: bundle config set PUPPET_GEM_VERSION '~> ${{ matrix.puppet_version }}.0'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run syntax validation
        run: bundle exec rake syntax

      - name: Run unit tests (subset)
        run: bundle exec rspec spec/unit/

      - name: Test Facter facts on platform
        run: |
          bundle exec ruby -I lib -e "
            require 'facter/antelope'
            puts 'Facter facts load correctly on ${{ matrix.os }}'
          "